### 웹 검색
POST http://localhost:8080/search
Content-Type: application/json

{
  "query": "백엔드 개발자"
}

### 벡터 디비 검색
POST http://localhost:8080/search/vector
Content-Type: application/json

{
  "query": ""
}
