### 웹 검색
POST http://localhost:8090/searching-assistant/
Content-Type: application/json

{
  "query": "2024년 백엔드 개발자 채용 통계"
}

### 벡터 디비 검색
POST http://localhost:8090/searching-assistant/vector
Content-Type: application/json

{
  "query": "백엔드 개발자 취업"
}


### 글 작성 도우미
POST http://localhost:8090/writing-assistant
Content-Type: application/json

{
  "text": "안녕 오늘 날씨는 좀 구린거 같아."
}


### Countires
GET localhost:8090/api/v1/countries?alpha2=DK
#GET localhost:8090/api/v1/countries?page=6&size=20&sortBy=name&sortDirection=ASC
#GET localhost:8090/api/v1/countries?page=1&size=20&sortBy=name&sortDirection=ASC&code=410&alpha2=KR&name=Korea
Content-Type: application/json


### Trade Stats Requests
GET localhost:8090/api/v1/countries/0194c057-34f8-c229-862c-253ae9ab5eda/trade-stats-requests?page=3
Content-Type: application/json


### Sync Trade Stats
PUT localhost:8090/api/v1/trade-stats-requests/0194c466-dacd-7465-7453-b1a4a3facfc8/sync
Content-Type: application/json
