package com.raynor.geek.client.tavily.dto

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.databind.annotation.JsonNaming

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
data class TavilySearchRequestDto(
    val apiKey: String,

    /* The search query you want to execute with Tavily. */
    val query: String,

    /* The depth of the search. It can be "basic" or "advanced". Default is "basic" unless specified otherwise in a given method. */
    val searchDepth: String? = null,

    /* The category of the search. This will determine which of our agents will be used for the search.
     * Currently: only "general" and "news" are supported. Default is "general". */
    val topic: String = "general",

    /* The number of days back from the current date to include in the search results.
     * This specifies the time frame of data to be retrieved.
     * Please note that this feature is only available when using the "news" search topic. Default is 3. */
    val days: Int? = null,

    /* The time range back from the current date to include in the search results.
     * Accepted values include "day","week","month","year" or "d","w","m","y". Default is None,
     * which will not filter search results by time range. */
    val timeRange: String? = null,

    /* The maximum number of search results to return. Default is 5. */
    val maxResults: Int = 10,

    /* Include a list of query-related images in the response. Default is False. */
    val includeImages: Boolean? = null,

    /* When include_images is set to True, this option adds descriptive text for each image. Default is False. */
    val includeImagesDescriptions: Boolean? = null,

    /* Include a short answer to original query, generated by an LLM based on Tavily's search results. Default is False. */
    val includeAnswer: Boolean? = null,

    /* Include the cleaned and parsed HTML content of each search result. Default is False. */
    val includeRawContent: Boolean? = null,

    /* A list of domains to specifically include in the search results. Default is [], which includes all domains. */
    val includeDomains: List<String>? = null,

    /* A list of domains to specifically exclude from the search results. Default is [], which doesn't exclude any domains. */
    val excludeDomains: List<String>? = null,
)
