spring.application.name: spring-ai-geek
spring.profiles.active: local
spring.web.resources.add-mappings: false

spring:
  config:
    import:
      - storage-rds.yaml
      - storage-memorydb.yaml
      - client.yaml
      - llm.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2KB
    excluded-user-agents: MSIE 6.0,UCBrowser

---
spring.config.activate.on-profile: local

spring:
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org.springframework: DEBUG

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: stage

---
spring.config.activate.on-profile: prod
