spring.application.name: about-spring-security-web
spring.profiles.active: local
spring.web.resources.add-mappings: false

spring:
  config:
    import:
      - storage-rds.yaml
      - storage-memorydb.yaml
      - client.yaml
  ai:
    ollama:
      init:
        timeout: 5m
        max-retries: 0
        pull-model-strategy: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2KB
    excluded-user-agents: MSIE 6.0,UCBrowser

---
spring.config.activate.on-profile: local

spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: exaone3.5:7.8b
      embedding:
        model: mxbai-embed-large:latest

    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "minioadmin"
          password: "minioadmin"

logging:
  level:
    org.springframework: DEBUG

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: stage

---
spring.config.activate.on-profile: prod
