---
spring.config.activate.on-profile: local

spring:
  ai:
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "root"
        auto-id: true
        database-name: "geek"
        collection-name: "geek_store"
        embedding-dimension: 1536
        index-type: ivf_flat
        metric-type: cosine

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: stage

---
spring.config.activate.on-profile: production
